- menu_name: "Quick Links"

- name: HPC Documentation
  url: https://arcdocs.leeds.ac.uk/
  title: Leeds HPC Documentation

- name: "University of Leeds IT Services"
  url: "https://it.leeds.ac.uk/it"
  title: "IT Services Page"

- name: "University of Leeds IT Knowledge Base"
  url: "https://it.leeds.ac.uk/it?id=index"
  title: "IT Knowledge Base Page"

- name: "Sitemap"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
