- menu_name: "Links"

- name: "Contact Us"
  url: "https://leeds.service-now.com/it?id=sc_cat_item&sys_id=7587b2530f675f00a82247ece1050eda"
  title: "Contact us via a ticket"

- name: "IT Knowledge Base"
  url: "https://it.leeds.ac.uk/it?id=index"
  title: "University of Leeds IT Knowledge Base"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
