widget:
  - title: 'HPC0: <br> Introduction to Linux <br> for HPC'
    url: /training/courses/hpc0
    text: This is a hands-on workshop intended as an introduction
           to the Linux command line and shell scripting.
    style: training-widget
    level: beginner
  - title: 'HPC1: <br> Introduction to High Performance Computing'
    url: /training/courses/hpc1
    text: |
           This workshop is designed to introduce new users to
           concepts of High Performance Computing (HPC) and the HPC service at Leeds.
    style: training-widget
    level: beginner
  - title: 'SWD1a: <br> Introduction to <br> Python programming'
    url: /training/courses/swd1a
    text: |
          This is an introduction to programming in Python for
          people with little or no previous programming experience.
    style: training-widget
    level: beginner

  - title: 'SWD1b: <br> Introduction to <br> R programming'
    url: /training/courses/swd1b
    text: |
          This is an introduction to programming in R
          for people with little or no previous programming experience.
    style: training-widget
    level: beginner

  - title: 'SWD2: <br> Version Control with Git and GitHub'
    url: /training/courses/swd2
    text: This is a hands-on workshop intended as an
          introduction to version control using git and GitHub.
    style: training-widget
    level: beginner
  - title: 'SWD3: <br> Software development practices for Research'
    url: /training/courses/swd3
    text: |
           A one-day workshop introducing techniques and concepts
           that professional software developers use to manage their code, projects and teams.
    style: training-widget
    level: beginner
  - title: 'HPC6: <br> HPC for Life Sciences and Bioinformatics'
    url: /training/courses/hpc6
    text: |
           A one-day workshop to introduce Biologists, Chemists and
           Bioinformaticians to the HPC facilities at Leeds.
    style: training-widget
    level: beginner

  # intermediate courses

  - title: 'HPC2: Applications and containers on HPC'
    url: /training/courses/hpc2
    text: |
          A one-day workshop introducing application
          development on the HPC service with hands on practice managing, installing and compiling code.
    style: training-widget
    level: intermediate
  - title: 'HPC3: Computer architectures and shared memory parallel programming'
    url: /training/courses/hpc3
    text: |
          A one-day workshop introducing the OpenMP
          parallel programming model with hands on practice developing and
          adapting code to run on shared memory machines.
    style: training-widget
    level: intermediate
  - title: 'HPC5: Introduction to GPU programming with CUDA'
    url: /training/courses/hpc5
    text: |
          A one-day workshop covering the  fundamentals of parallel computing
          with GPUs and the CUDA programming environment.
    style: training-widget
    level: intermediate
  - title: 'SWD4: Cloud computing for Research'
    url: /training/courses/swd4
    text: |
          An introduction to Cloud computing services for researchers especially
          with regard to High Performance Computing and Big Data analysis.
    style: training-widget
    level: intermediate
  - title: 'SWD5: Scientific Python'
    url: /training/courses/swd5
    text: |
          A one-day workshop on Python’s main Scientific libraries
          (Scipy, Numpy and Matplotlib) and covering how to link existing
          C and Fortran codes and subroutines within Python code.
    style: training-widget
    level: intermediate
  - title: 'SWD6: <br> High performance Python'
    url: /training/courses/swd6
    text: |
          A hands-on workshop covering the use of a set of tools and techniques aimed
          at improving the execution speed of your Python code.
    style: training-widget
    level: intermediate
  - title: 'SWD7: Introduction to reproducible workflows in Python'
    url: /training/courses/swd7
    text: |
          A one-day workshop covering best practises for reproducible scientific
          code development and how to implement these into their day-to-day Python
          workflows.
    style: training-widget
    level: intermediate
