name: Merge Schedule
on:
  pull_request:
    branches:
      - master
  schedule:
    # https://crontab.guru/every-hour
    - cron: 0 0,6,12,23 * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
